### ISSUE TITLE
Not compatible with standard Queue().

### ISSUE THREAD

**Issue by folkien** [Invarato/quick_queue_project#1]
Missing functionality of methods : 
- .join()
- .task_done()

Could you fix it?

**Comment by Invarato** [comment]
Hi Folkien.
Yes, I am going to test these methods.
Thanks for feedback.

**Comment by Invarato** [comment]
In this project I use `multiprocessing.Queue` (https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues) and not `Queue.Queue` (https://docs.python.org/3/library/queue.html#queue-objects), they have different interfaces. `multiprocessing.Queue` have a `JoinableQueue` with `join` and `task_done` methods.

I have updated to 1.0.7 version with QueueJoinableQueue, this inherits from `JoinableQueue` and `QuickQueue`.
